front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

seleccionar_tramite:
    path:     /seleccionar-tipo-tramite/{opcion}
    defaults: { _controller: FrontBundle:Default:seleccionarTipoTramite }
    requirements:
      sinTurno: \d+

seleccionar_sede:
    path:     /seleccionar-sede
    defaults: { _controller: FrontBundle:Default:seleccionarSede }

elegir_turno:
    path:     /elegir-turno
    defaults: { _controller: FrontBundle:Default:elegirTurno }

ingreso_datos:
    path:     /ingreso-datos
    defaults: { _controller: FrontBundle:Default:ingresoDatos }

generar_comprobante:
    path:     /generar-comprobante/{hash}
    defaults: { _controller: FrontBundle:Default:generarComprobante }

cancelar_turno:
    path:     /cancelar-turno/{hash}
    defaults: { _controller: FrontBundle:Default:cancelarTurno }

procesar_cancelacion_turno:
    path: /procesar-cancelacion-turno/{id}
    defaults: { _controller: FrontBundle:Default:procesarCancelacionTurno }
    methods:  POST

## AJAX ACTIONS ##
get_tipo_tramite:
    path:     get-tipo-tramite
    defaults: { _controller: FrontBundle:Ajax:getTipoTramite }


get_horarios:
    path:     get-horarios
    defaults: { _controller: FrontBundle:Ajax:getHorarios }

pre_reserva:
    path:     pre-reserva
    defaults: { _controller: FrontBundle:Ajax:postPreReserva }
    methods: ['POST']

redis:
    path:     /redis
    defaults: { _controller: FrontBundle:Default:redis }
redis_agrega:
    path:     /redis_agrega
    defaults: { _controller: FrontBundle:Default:agregaCola }
redis_saca:
    path:     /redis_saca
    defaults: { _controller: FrontBundle:Default:sacaCola }
