imports:
    - { resource: config.yml }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            #resources: ['bootstrap_3_layout.html.twig']
            - 'bootstrap_3_horizontal_layout.html.twig'