services:
    manager.turnos:
        class:        AdminBundle\Services\TurnosManager
        autowire: true
        calls:
          - [ setSecret, ['%secret%']]
          - [ setMailer, ['@mailer']]
          - [ setRouter, ['@router' ]]


    manager.disponibilidad:
        class:        AdminBundle\Services\DisponibilidadManager
        autowire: true
        calls:
          - [ setMesAtincipacionTurnos, ['%mes_anticipacion_turnos%']]

    manager.usuario:
        class:        AdminBundle\Services\UsuarioManager
        autowire: true

    manager.util:
        class:        AdminBundle\Services\UtilManager
        autowire: true
