services:
    manager.turnos:
        class:        AdminBundle\Services\TurnosManager
        autowire: true

    manager.disponibilidad:
        class:        AdminBundle\Services\DisponibilidadManager
        autowire: true

    manager.usuario:
        class:        AdminBundle\Services\UsuarioManager
        autowire: true

    manager.util:
        class:        AdminBundle\Services\UtilManager
        autowire: true