services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    AdminBundle\:
          resource: '../../../../src/AdminBundle/*'
          # you can exclude directories or files
          # but if a service is unused, it's removed anyway
          exclude: '../../../../src/AdminBundle/{Entity,Repository,Tests,Form,Controller,AdminBundle.php}'

    AdminBundle\Services\TurnosManager:
        calls:
          - [ setSecret, ['%secret%']]
          - [ setMailer, ['@mailer']]
          - [ setRouter, ['@router' ]]

    AdminBundle\Services\DisponibilidadManager:
        calls:
          - [ setMesAtincipacionTurnos, ['%mes_anticipacion_turnos%']]


    manager.turnos:
        alias:  AdminBundle\Services\TurnosManager
        public: true

    manager.disponibilidad:
        alias: AdminBundle\Services\DisponibilidadManager
        public: true

    manager.util:
        alias: AdminBundle\Services\UtilManager
        public: true

    manager.usuario:
        alias: AdminBundle\Services\UsuarioManager
        public: true


    # authentication success event listener
    AdminBundle\EventListener\AuthenticationListener:
        tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }
        calls:
                  - [ setServiceContainer, [ '@service_container' ]]

    milentar.security.interactive_login_listener:
        alias: AdminBundle\EventListener\AuthenticationListener
        public: true


    Doctrine\ORM\EntityManager:
        alias: doctrine.orm.default_entity_manager
