# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  session.handler.pdo:
          class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
          public:    false
          arguments:
              - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
              - { db_username: '%database_user%', db_password: '%database_password%' }



  # authentication success event listener
  milentar.security.interactive_login_listener:
          class: AdminBundle\EventListener\AuthenticationListener
          tags:
              - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }