<?php
/**
 * Created by PhpStorm.
 * User: Fernando
 * Date: 18/03/2017
 * Time: 17:45
 */

namespace AdminBundle\Repository;

/**
 * ColaTurnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColaTurnoRepository extends \Doctrine\ORM\EntityRepository
{

    public function getTurno($turno)
    {
        $qb = $this->createQueryBuilder('ct')
            ->where('ct.turno = :turno')
            ->setParameter("turno", $turno)
            ->getQuery();

        return  $qb->getResult();
    }

}