<?php
/**
 * Created by PhpStorm.
 * User: Fernando
 * Date: 18/03/2017
 * Time: 17:52
 */

namespace AdminBundle\Repository;

/**
 * SedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SedeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSedesByTipoTramite($tipoTramite, $hidrate_array = false)
    {
        $qb = $this->createQueryBuilder('s')
          ->innerJoin('s.sedeTipoTramite', 'tt')
          ->where('tt.tipoTramite =:tipo_tramite')
          ->setParameter('tipo_tramite', $tipoTramite)
          ->getQuery();

        return $hidrate_array ? $qb->getArrayResult() : $qb->getResult();
    }
}
