<?php

namespace AdminBundle\Repository;

/**
 * TurnosSedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnosSedeRepository extends \Doctrine\ORM\EntityRepository
{
}
