<?php
/**
 * Created by PhpStorm.
 * User: Fernando
 * Date: 18/03/2017
 * Time: 18:00
 */

namespace AdminBundle\Repository;

/**
 * UsuarioSedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioSedeRepository extends \Doctrine\ORM\EntityRepository
{

}