box_index:
    path:     /
    defaults: { _controller: "AdminBundle:Box:index" }
    methods:  GET

box_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Box:show" }
    methods:  GET

box_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Box:new" }
    methods:  [GET, POST]

box_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Box:edit" }
    methods:  [GET, POST]

box_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Box:delete" }
    methods:  DELETE
