app_box_atencion_seleccion_box:
    path:     /seleccion-box
    defaults: { _controller: "AdminBundle:TurnoBox:seleccionBox" }
    methods:  [GET, POST]

app_box_atencion_box:
    path:     /atencion-box
    defaults: { _controller: "AdminBundle:TurnoBox:atencionBox" }
    methods:  [GET, POST]

app_box_nuevo_turno:
    path:     /obtener-proximo
    defaults: { _controller: "AdminBundle:TurnoBox:obtenerProximo" }
    methods:  [GET, POST]

app_box_volver_llamar_turno:
    path:     /volver-llamar
    defaults: { _controller: "AdminBundle:TurnoBox:volverLLamar" }
    methods:  [GET, POST]

app_box_cambiar_box:
    path:     /cambiar-box
    defaults: { _controller: "AdminBundle:TurnoBox:cambiarBox" }
    methods:  GET

app_box_turno_atendido:
    path:       /turno-atendido/{id}
    defaults:   { _controller: "AdminBundle:TurnoBox:turnoAtendido"}
    methods:    GET