turno_administrar:
    path:     /
    defaults: { _controller: "AdminBundle:Turno:administrar" }
    methods:  [GET, POST]

turno_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Turno:show" }
    methods:  GET

turno_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Turno:new" }
    methods:  [GET, POST]

turno_new_prioritario:
    path:     /new-prioritario
    defaults: { _controller: "AdminBundle:Turno:newPrioritario" }
    methods:  [GET, POST]

turno_confirmar:
    path:     /{id}/confirmar
    defaults: { _controller: "AdminBundle:Turno:confirmarTurno" }
    methods:  [GET, POST]

turno_show_prioritario:
    path:     /{id}/show-prioritario
    defaults: { _controller: "AdminBundle:Turno:showPrioritario" }
    methods:  GET

turno_confirmar_prioritario:
    path:     /{id}/confirmar-prioritario
    defaults: { _controller: "AdminBundle:Turno:confirmarTurnoPrioritario" }
    methods:  [GET, POST]

turno_imprimir:
    path:     /{id}/imprimir
    defaults: { _controller: "AdminBundle:Turno:imprimir" }
    methods:  GET

turno_cancelar:
    path:     /{id}/concelar-turno
    defaults: { _controller: "AdminBundle:Turno:cancelar" }
    methods:  GET

turno_procesa_cancelar:
    path:     /{id}/procesar-cancela-turno
    defaults: { _controller: "AdminBundle:Turno:procesarCancelar" }
    methods:  [GET, POST]