turnotipotramite_index:
    path:     /
    defaults: { _controller: "AdminBundle:TurnoTipoTramite:index" }
    methods:  GET

turnotipotramite_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:TurnoTipoTramite:show" }
    methods:  GET

turnotipotramite_new:
    path:     /new
    defaults: { _controller: "AdminBundle:TurnoTipoTramite:new" }
    methods:  [GET, POST]

turnotipotramite_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:TurnoTipoTramite:edit" }
    methods:  [GET, POST]

turnotipotramite_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:TurnoTipoTramite:delete" }
    methods:  DELETE
