turnossede_index:
    path:     /
    defaults: { _controller: "AdminBundle:TurnosSede:index" }
    methods:  GET

turnossede_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:TurnosSede:show" }
    methods:  GET

turnossede_new:
    path:     /new
    defaults: { _controller: "AdminBundle:TurnosSede:new" }
    methods:  [GET, POST]

turnossede_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:TurnosSede:edit" }
    methods:  [GET, POST]

turnossede_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:TurnosSede:delete" }
    methods:  DELETE
