turnosede_index:
    path:     /
    defaults: { _controller: "AdminBundle:TurnoSede:index" }
    methods:  GET

turnosede_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:TurnoSede:show" }
    methods:  GET

turnosede_new:
    path:     /new
    defaults: { _controller: "AdminBundle:TurnoSede:new" }
    methods:  [GET, POST]

turnosede_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:TurnoSede:edit" }
    methods:  [GET, POST]

turnosede_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:TurnoSede:delete" }
    methods:  DELETE
