acl:
  ROLE_USER:
      admin_homepage: true
      cambiar-password: true
      usuario_acceso_denegado: true
      front_homepage:  true
      seleccionar_tramite: true
      seleccionar_sede: true
      elegir_turno: true
      ingreso_datos: true
      generar_comprobante: true
      cancelar_turno: true
      get_tipo_tramite: true
      get_horarios: true
      pre_reserva: true

  ROLE_SEDE:
      turno_administrar: true
      turno_show: true
      turno_new: true
      turno_new_prioritario: true
      turno_confirmar: true
      turno_show_prioritario: true
      turno_confirmar_prioritario: true
      turno_imprimir: true
      turno_cancelar: true
      turno_procesa_cancelar: true

  ROLE_PARAMETRIZAR:
      usuario_index: true
      usuario_show:  true
      usuario_new:  true
      usuario_edit: true
      usuario_delete: true
      usuario_cambiar_password: true
      box_index: true
      box_show: true
      box_new: true
      box_edit: true
      box_delete: true
      cancelacionmasiva_index: true
      cancelacionmasiva_show: true
      cancelacionmasiva_new: true
      cancelacionmasiva_edit: true
      cancelacionmasiva_delete: true
      feriado_index: true
      feriado_show: true
      feriado_new: true
      feriado_edit: true
      feriado_delete: true
      sede_index: true
      sede_show: true
      sede_new: true
      sede_edit: true
      sede_delete: true
      texto_mail_index: true
      texto_mail_show: true
      texto_mail_new: true
      texto_mail_edit: true
      texto_mail_delete: true
      tipotramite_index: true
      tipotramite_show: true
      tipotramite_new: true
      tipotramite_edit: true
      tipotramite_delete: true
      turnosede_index: true
      turnosede_show: true
      turnosede_new: true
      turnosede_edit: true
      turnosede_delete: true
      turnotipotramite_index: true
      turnotipotramite_show: true
      turnotipotramite_new: true
      turnotipotramite_edit: true
      turnotipotramite_delete: true
      usuariosede_index: true
      usuariosede_show: true
      usuariosede_new: true
      usuariosede_edit: true
      usuariosede_delete: true
      usuarioturnosede_index: true
      usuarioturnosede_show: true
      usuarioturnosede_new: true
      usuarioturnosede_edit: true
      usuarioturnosede_delete: true
      turnosedeusuariotipotramite_index: true
      turnosedeusuariotipotramite_show: true
      turnosedeusuariotipotramite_new: true
      turnosedeusuariotipotramite_edit: true
      opciongeneral_index: true
      opciongeneral_show: true
      opciongeneral_new: true
      opciongeneral_edit: true
      opciongeneral_delete: true