user_usuario:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /usuario

user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }


cambiar-password:
    path:     /cambiar-password
    defaults: { _controller: UserBundle:CambiarPassword:cambiarPassword }


usuario_acceso_denegado:
    path: /acceso-denegado
    defaults: { _controller: UserBundle:Default:accessDenied}