/*
-- Query: select * from tipo_tramite
LIMIT 0, 300

-- Date: 2017-03-30 18:05
*/
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (1,1,1,'Renuncia Ordinaria','<p>Obligatorio (presentar por duplicado):&nbsp;</p>\r\n\r\n<ul>\r\n	<li>Formulario Cese Ordinario.</li>\r\n	<li>Declaraci&oacute;n Jurada o Formulario Datos personales e Historia Laboral.&nbsp;</li>\r\n	<li>Formulario de Servicios Prestados Fuera de la DGCyE.</li>\r\n	<li>Formulario Declaraci&oacute;n Jurada de Anticipo (voluntario). Copia de Documento Nacional de Identidad. &Uacute;ltimo Recibo de Haberes.</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Opcional:</p>\r\n\r\n<ul>\r\n	<li>Formulario Poder (gestores o gremios).</li>\r\n	<li>Resoluciones de designaciones y bajas, constancias de Ruralidad/Desfavorabilidad, Doble Escolaridad, Jornada Completa, Jornada Extendida, Escuela C&aacute;rcel, R&eacute;gimen de 40 hs. y dem&aacute;s bonificaciones o adicionales que impacten sobre el mejor cargo.</li>\r\n</ul>',NULL,NULL,NULL,NULL,1,'2017-03-22 22:26:38','2017-03-26 19:44:52',0,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (2,1,1,'Jubilación Automática Docente','<p>Obligatorio (presentar por triplicado):   Formulario Cese Ordinario.  Declaración Jurada o Formulario Datos personales e Historia Laboral.   Formulario de Servicios Prestados Fuera de la DGCyE.  Copia de Documento Nacional de Identidad.  Último Recibo de Haberes. </p>   <p> Opcional:  Formulario Poder (gestores o gremios).  Resoluciones de designaciones y bajas, constancias de  Ruralidad/Desfavorabildiad, Doble Escolaridad, Jornada Completa, Jornada Extendida,  Escuela Cárcel, Régimen de 40 hs. y demás bonificaciones o adicionales que  impacten sobre el mejor cargo.</p>',NULL,NULL,NULL,NULL,1,'2017-03-22 22:30:05','2017-03-22 22:30:05',0,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (3,1,1,'Cierre condicionado de cómputos. Caja Jubilatoria IPS','<p>Obligatorio (presentar por duplicado):  Formulario Cierre Condicionado de Cómputos.  Formulario Datos personales e Historia Laboral  Formulario de servicios prestados fuera de la DGCyE  Copia de Documento Nacional de Identidad.  Último Recibo de Haberes. .</p>    .<p>Opcional:  Formulario Poder (gestores o gremios).  Resoluciones de designaciones y bajas, constancias de  Ruralidad/Desfavorabildiad, Doble Escolaridad, Jornada Completa, Jornada Extendida,  Escuela Cárcel, Régimen de 40 hs. y demás bonificaciones o adicionales que  impacten sobre el mejor cargo.</p>',NULL,NULL,NULL,NULL,1,'2017-03-22 22:31:10','2017-03-22 22:31:10',0,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (4,1,1,'Cierre de Cómputos Transferidos. Caja Jubilatoria NO IPS','<p>Obligatorio (presentar por duplicado):  Formulario Cierre Condicionado de Cómputos.  Formulario Datos personales e Historia Laboral  Formulario de servicios prestados fuera de la DGCyE  Copia de Documento Nacional de Identidad.  Último Recibo de Haberes.</p>     <p>Opcional:  Formulario Poder (gestores o gremios).  Resoluciones de designaciones y bajas, constancias de  Ruralidad/Desfavorabildiad, Doble Escolaridad, Jornada Completa, Jornada Extendida,  Escuela Cárcel, Régimen de 40 hs. y demás bonificaciones o adicionales que  impacten sobre el mejor cargo. </p>',NULL,NULL,NULL,NULL,1,'2017-03-22 22:32:27','2017-03-22 22:32:27',0,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (5,1,1,'Ejecutiva Validando con sector.',NULL,NULL,NULL,NULL,NULL,1,'2017-03-22 22:33:39','2017-03-22 22:33:39',0,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (6,1,1,'Pensión','<p>Obligatorio (presentar por duplicado):               Nota Solicitando Pensión Rubricada por derecho habiente/s.                  Formulario Datos personales e Historia Laboral                  Certificado de Defunción Autenticado. (Ej. Escribano Público, Registro  Público de Comercio, Juez de Paz).                  Certificado Autenticado de Acreditación del Vínculo. (Ej. Certificado/Partida  de Matrimonio, Nacimiento.)                  Copia de Documento Nacional de Identidad del Beneficiario.                  Copia de Documento Nacional de Identidad del Fallecido.</p>  <p>Opcional:  Formulario Poder (gestores o gremios).  Resoluciones de designaciones y bajas, constancias de  Ruralidad/Desfavorabildiad, Doble Escolaridad, Jornada Completa, Jornada Extendida,  Escuela Cárcel, Régimen de 40 hs. y demás bonificaciones o adicionales que  impacten sobre el mejor cargo.   Último Recibo de Haberes.</p>',NULL,NULL,NULL,NULL,1,'2017-03-22 22:35:08','2017-03-22 22:35:08',0,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (7,1,1,'Certificación de servicios con fines previsionales (agente cesados en la  DGCyE)','<p>Obligatorio (presentar por duplicado):  Formulario Datos personales e Historial Laboral.  Formulario Mejor Cargo.  Copia de Documento Nacional de Identidad.  Último Recibo de Haberes.  </p>  <p> Opcional:  Formulario Poder (gestores o gremios).  Resoluciones de designaciones y bajas, constancias de  Ruralidad/Desfavorabildiad, Doble Escolaridad, Jornada Completa, Jornada Extendida,  Escuela Cárcel, Régimen de 40 hs. y demás bonificaciones o adicionales que  impacten sobre el mejor cargo.</p>',NULL,NULL,NULL,NULL,1,'2017-03-22 22:36:22','2017-03-22 22:36:22',0,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (8,1,1,'Certificación de servicios sin fines previsionales','<p>Obligatorio (presentar por duplicado):  Copia de Documento Nacional de Identidad.  Último Recibo de Haberes.  Requerimiento del Organismo Destinatario (en caso de corresponder)</p>',NULL,NULL,NULL,NULL,1,'2017-03-22 22:37:12','2017-03-22 22:37:12',0,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (9,1,1,'Jubilación por Invalidez. Validando','<p>El expediente no se inicia en la Dirección de Jubilaciones y Certificaciones. El Instituto  de Previsión Social remite el expediente con el resultado de la Junta Médica a los  efectos de que la DJyC cargue el Cese por Invalidez, confecciones la Certificación de  Servicios y proyecte el Acto Administrativo de Cese.</p>',NULL,NULL,NULL,NULL,1,'2017-03-22 22:37:57','2017-03-22 22:39:11',1,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (10,1,1,'Retiro de Códigos',NULL,NULL,NULL,NULL,NULL,1,'2017-03-22 22:39:35','2017-03-22 22:39:35',1,NULL,NULL,'');
INSERT INTO `tipo_tramite` (`id`,`creado_por_id`,`actualizado_por_id`,`descripcion`,`texto`,`documento1`,`documento2`,`documento3`,`documento4`,`activo`,`fecha_creacion`,`fecha_actualizacion`,`sin_turno`,`documento5`,`documento6`,`slug`) VALUES (11,1,1,'Caja Complementaria.',NULL,NULL,NULL,NULL,NULL,1,'2017-03-22 22:39:55','2017-03-22 22:39:55',1,NULL,NULL,'');
